travis: try to avoid running coverity if token isn't set (anyone but me)

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -29,6 +29,7 @@ script:
   - touch configure.ac Makefile.am aclocal.m4 configure Makefile.in config.h.in
   - |
     if [[ ${CC} == coverity ]] ; then
+      [[ -n ${COVERITY_SCAN_TOKEN} ]] || exit 0;  # don't fail on this for PRs
       # ensure we end up with an existing compiler
       export CC=gcc
       ./configure || { cat config.log ; exit 1 ; }
